import { CollegeConfig, Subject } from '../types/timetable';

export interface PresetData {
  id: string;
  name: string;
  badge: string;
  description: string;
  config: CollegeConfig;
  subjects: Subject[];
}

export const PRESETS: PresetData[] = [
  {
    id: 'preset-7-periods',
    name: 'Engineering College (7 Periods / Day)',
    badge: '7 Periods • Mon–Fri',
    description: 'Computer Science Dept • 50-min periods • 3-period lab sessions • Morning tea & Lunch breaks',
    config: {
      collegeName: 'Apex Institute of Technology & Engineering',
      department: 'Computer Science & Engineering',
      semester: 'Semester 5',
      academicYear: '2026-2027',
      section: 'Section A',
      workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      startTime: '09:00',
      targetEndTime: '16:15',
      periodsPerDay: 7,
      periodDuration: 50,
      breaks: [
        {
          id: 'brk-1',
          name: 'Tea Break',
          afterPeriod: 2,
          duration: 15,
          type: 'short',
        },
        {
          id: 'brk-2',
          name: 'Lunch Break',
          afterPeriod: 4,
          duration: 50,
          type: 'lunch',
        },
      ],
      defaultRoom: 'Room LH-201',
    },
    subjects: [
      {
        id: 'sub-cs501',
        code: 'CS501',
        name: 'Database Management Systems',
        facultyName: 'Dr. Aris Vance',
        weeklyPeriods: 4,
        type: 'theory',
        labDuration: 1,
        room: 'Room LH-201',
        color: '#3b82f6', // blue
      },
      {
        id: 'sub-cs502',
        code: 'CS502',
        name: 'Operating Systems & Architecture',
        facultyName: 'Prof. Elena Rostova',
        weeklyPeriods: 4,
        type: 'theory',
        labDuration: 1,
        room: 'Room LH-201',
        color: '#10b981', // emerald
      },
      {
        id: 'sub-cs503',
        code: 'CS503',
        name: 'Computer Networks & Security',
        facultyName: 'Dr. Marcus Sterling',
        weeklyPeriods: 4,
        type: 'theory',
        labDuration: 1,
        room: 'Room LH-201',
        color: '#8b5cf6', // purple
      },
      {
        id: 'sub-cs504',
        code: 'CS504',
        name: 'Theory of Computation',
        facultyName: 'Prof. David Chen',
        weeklyPeriods: 4,
        type: 'theory',
        labDuration: 1,
        room: 'Room LH-201',
        color: '#f59e0b', // amber
      },
      {
        id: 'sub-cs505',
        code: 'CS505',
        name: 'Software Engineering & Agile',
        facultyName: 'Dr. Sarah Jenkins',
        weeklyPeriods: 3,
        type: 'theory',
        labDuration: 1,
        room: 'Room LH-201',
        color: '#ec4899', // pink
      },
      {
        id: 'sub-cs501l',
        code: 'CS501L',
        name: 'DBMS & SQL Laboratory',
        facultyName: 'Dr. Aris Vance',
        weeklyPeriods: 3,
        type: 'lab',
        labDuration: 3,
        room: 'Computing Lab 3',
        color: '#0284c7', // sky
      },
      {
        id: 'sub-cs502l',
        code: 'CS502L',
        name: 'OS & Linux Kernel Lab',
        facultyName: 'Prof. Elena Rostova',
        weeklyPeriods: 3,
        type: 'lab',
        labDuration: 3,
        room: 'Systems Lab 1',
        color: '#059669', // green
      },
      {
        id: 'sub-cs503l',
        code: 'CS503L',
        name: 'Network Protocols Lab',
        facultyName: 'Dr. Marcus Sterling',
        weeklyPeriods: 3,
        type: 'lab',
        labDuration: 3,
        room: 'Networks Lab 2',
        color: '#7c3aed', // violet
      },
      {
        id: 'sub-cs506',
        code: 'CS506',
        name: 'Technical Seminar & Soft Skills',
        facultyName: 'Prof. David Chen',
        weeklyPeriods: 2,
        type: 'seminar',
        labDuration: 1,
        room: 'Seminar Hall B',
        color: '#d97706', // orange
      },
      {
        id: 'sub-cs507',
        code: 'CS507',
        name: 'Aptitude & Placement Mentoring',
        facultyName: 'Dr. Sarah Jenkins',
        weeklyPeriods: 2,
        type: 'tutorial',
        labDuration: 1,
        room: 'Room LH-201',
        color: '#64748b', // slate
      },
    ],
  },
  {
    id: 'preset-8-periods',
    name: 'Polytechnic & Tech Institute (8 Periods / Day)',
    badge: '8 Periods • Mon–Sat',
    description: 'Mechanical & Automation • 45-min periods • 2-period practical workshops • 6 working days',
    config: {
      collegeName: 'State Polytechnic Institute of Technology',
      department: 'Mechanical & Automation Engineering',
      semester: 'Semester 4',
      academicYear: '2026-2027',
      section: 'Section B',
      workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      startTime: '08:30',
      targetEndTime: '15:45',
      periodsPerDay: 8,
      periodDuration: 45,
      breaks: [
        {
          id: 'brk-1',
          name: 'Morning Break',
          afterPeriod: 2,
          duration: 15,
          type: 'short',
        },
        {
          id: 'brk-2',
          name: 'Lunch Break',
          afterPeriod: 4,
          duration: 45,
          type: 'lunch',
        },
        {
          id: 'brk-3',
          name: 'Afternoon Break',
          afterPeriod: 6,
          duration: 15,
          type: 'short',
        },
      ],
      defaultRoom: 'Hall M-104',
    },
    subjects: [
      {
        id: 'sub-me401',
        code: 'ME401',
        name: 'Thermodynamics & Heat Transfer',
        facultyName: 'Dr. Raymond Clark',
        weeklyPeriods: 6,
        type: 'theory',
        labDuration: 1,
        room: 'Hall M-104',
        color: '#ef4444', // red
      },
      {
        id: 'sub-me402',
        code: 'ME402',
        name: 'Fluid Mechanics & Machinery',
        facultyName: 'Prof. Angela Yu',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Hall M-104',
        color: '#3b82f6', // blue
      },
      {
        id: 'sub-me403',
        code: 'ME403',
        name: 'Manufacturing Technology',
        facultyName: 'Dr. Harold Finch',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Hall M-104',
        color: '#10b981', // green
      },
      {
        id: 'sub-me404',
        code: 'ME404',
        name: 'Kinematics of Machines',
        facultyName: 'Prof. Simon Baker',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Hall M-104',
        color: '#8b5cf6', // purple
      },
      {
        id: 'sub-me405',
        code: 'ME405',
        name: 'Engineering Mathematics IV',
        facultyName: 'Dr. Lisa Taylor',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Hall M-104',
        color: '#f59e0b', // amber
      },
      {
        id: 'sub-me401l',
        code: 'ME401L',
        name: 'Thermal Engineering Lab',
        facultyName: 'Dr. Raymond Clark',
        weeklyPeriods: 4,
        type: 'lab',
        labDuration: 2,
        room: 'Thermal Lab',
        color: '#dc2626',
      },
      {
        id: 'sub-me402l',
        code: 'ME402L',
        name: 'Fluid Mechanics Workshop',
        facultyName: 'Prof. Angela Yu',
        weeklyPeriods: 4,
        type: 'lab',
        labDuration: 2,
        room: 'Hydraulics Workshop',
        color: '#2563eb',
      },
      {
        id: 'sub-me403l',
        code: 'ME403L',
        name: 'CNC & Machine Tools Lab',
        facultyName: 'Dr. Harold Finch',
        weeklyPeriods: 4,
        type: 'lab',
        labDuration: 2,
        room: 'Central Workshop',
        color: '#059669',
      },
      {
        id: 'sub-me406',
        code: 'ME406',
        name: 'CAD / CAM Drafting',
        facultyName: 'Prof. Simon Baker',
        weeklyPeriods: 4,
        type: 'lab',
        labDuration: 2,
        room: 'CAD Computer Lab',
        color: '#7c3aed',
      },
      {
        id: 'sub-me407',
        code: 'ME407',
        name: 'Industrial Safety & Ethics',
        facultyName: 'Dr. Lisa Taylor',
        weeklyPeriods: 3,
        type: 'seminar',
        labDuration: 1,
        room: 'Hall M-104',
        color: '#d97706',
      },
    ],
  },
  {
    id: 'preset-6-periods',
    name: 'Liberal Arts & Science College (6 Periods / Day)',
    badge: '6 Periods • Mon–Fri',
    description: 'Biotechnology & Genetics • 55-min periods • 2-period lab block • Single mid-day lunch break',
    config: {
      collegeName: 'Saint Xavier College of Arts & Sciences',
      department: 'Department of Biotechnology',
      semester: 'Semester 3',
      academicYear: '2026-2027',
      section: 'Section Alpha',
      workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      startTime: '09:30',
      targetEndTime: '16:00',
      periodsPerDay: 6,
      periodDuration: 55,
      breaks: [
        {
          id: 'brk-1',
          name: 'Lunch Break',
          afterPeriod: 3,
          duration: 45,
          type: 'lunch',
        },
      ],
      defaultRoom: 'Bio Lecture Hall 12',
    },
    subjects: [
      {
        id: 'sub-bt301',
        code: 'BT301',
        name: 'Molecular Biology & Genetics',
        facultyName: 'Dr. Claire Bennett',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Bio Lecture Hall 12',
        color: '#0284c7',
      },
      {
        id: 'sub-bt302',
        code: 'BT302',
        name: 'Biochemistry & Enzymology',
        facultyName: 'Dr. Arthur Pendelton',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Bio Lecture Hall 12',
        color: '#10b981',
      },
      {
        id: 'sub-bt303',
        code: 'BT303',
        name: 'Microbiology & Immunology',
        facultyName: 'Prof. Maya Lin',
        weeklyPeriods: 4,
        type: 'theory',
        labDuration: 1,
        room: 'Bio Lecture Hall 12',
        color: '#8b5cf6',
      },
      {
        id: 'sub-bt304',
        code: 'BT304',
        name: 'Biostatistics & Research Methods',
        facultyName: 'Dr. Samuel Green',
        weeklyPeriods: 4,
        type: 'theory',
        labDuration: 1,
        room: 'Bio Lecture Hall 12',
        color: '#f59e0b',
      },
      {
        id: 'sub-bt301l',
        code: 'BT301L',
        name: 'Molecular Biology Lab',
        facultyName: 'Dr. Claire Bennett',
        weeklyPeriods: 4,
        type: 'lab',
        labDuration: 2,
        room: 'Genetics Lab 4',
        color: '#0369a1',
      },
      {
        id: 'sub-bt302l',
        code: 'BT302L',
        name: 'Biochemistry Practical',
        facultyName: 'Dr. Arthur Pendelton',
        weeklyPeriods: 4,
        type: 'lab',
        labDuration: 2,
        room: 'Biochem Lab 2',
        color: '#047857',
      },
      {
        id: 'sub-bt305',
        code: 'BT305',
        name: 'Bioethics & Journal Club',
        facultyName: 'Prof. Maya Lin',
        weeklyPeriods: 2,
        type: 'seminar',
        labDuration: 1,
        room: 'Bio Lecture Hall 12',
        color: '#7c3aed',
      },
    ],
  },
  {
    id: 'preset-9-periods',
    name: 'Metropolitan University (9 Periods / Day)',
    badge: '9 Periods • Mon–Fri',
    description: 'Electronics & Communication • 40-min periods • 3-period VLSI lab • 2 breaks & Lunch',
    config: {
      collegeName: 'Metropolitan Institute of Technology',
      department: 'Electronics & Communication Engineering',
      semester: 'Semester 6',
      academicYear: '2026-2027',
      section: 'Section A',
      workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      startTime: '08:15',
      targetEndTime: '15:45',
      periodsPerDay: 9,
      periodDuration: 40,
      breaks: [
        {
          id: 'brk-1',
          name: 'Morning Tea',
          afterPeriod: 3,
          duration: 15,
          type: 'short',
        },
        {
          id: 'brk-2',
          name: 'Lunch Break',
          afterPeriod: 5,
          duration: 45,
          type: 'lunch',
        },
        {
          id: 'brk-3',
          name: 'Afternoon Tea',
          afterPeriod: 7,
          duration: 10,
          type: 'short',
        },
      ],
      defaultRoom: 'Room ECE-305',
    },
    subjects: [
      {
        id: 'sub-ec601',
        code: 'EC601',
        name: 'VLSI Design & Architecture',
        facultyName: 'Dr. Jonathan Ross',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Room ECE-305',
        color: '#3b82f6',
      },
      {
        id: 'sub-ec602',
        code: 'EC602',
        name: 'Embedded Systems & IoT',
        facultyName: 'Prof. Ananya Sen',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Room ECE-305',
        color: '#10b981',
      },
      {
        id: 'sub-ec603',
        code: 'EC603',
        name: 'Digital Signal Processing',
        facultyName: 'Dr. Victor Morales',
        weeklyPeriods: 5,
        type: 'theory',
        labDuration: 1,
        room: 'Room ECE-305',
        color: '#8b5cf6',
      },
      {
        id: 'sub-ec604',
        code: 'EC604',
        name: 'Antenna & Wave Propagation',
        facultyName: 'Prof. Rachel Adams',
        weeklyPeriods: 4,
        type: 'theory',
        labDuration: 1,
        room: 'Room ECE-305',
        color: '#f59e0b',
      },
      {
        id: 'sub-ec605',
        code: 'EC605',
        name: 'Control Systems Engineering',
        facultyName: 'Dr. Kevin Zhao',
        weeklyPeriods: 4,
        type: 'theory',
        labDuration: 1,
        room: 'Room ECE-305',
        color: '#ec4899',
      },
      {
        id: 'sub-ec601l',
        code: 'EC601L',
        name: 'VLSI & EDA Tools Lab',
        facultyName: 'Dr. Jonathan Ross',
        weeklyPeriods: 6,
        type: 'lab',
        labDuration: 3,
        room: 'VLSI Silicon Lab',
        color: '#2563eb',
      },
      {
        id: 'sub-ec602l',
        code: 'EC602L',
        name: 'Embedded Systems & ARM Lab',
        facultyName: 'Prof. Ananya Sen',
        weeklyPeriods: 6,
        type: 'lab',
        labDuration: 3,
        room: 'Embedded Systems Lab',
        color: '#059669',
      },
      {
        id: 'sub-ec606',
        code: 'EC606',
        name: 'Project Work & Review',
        facultyName: 'Dr. Victor Morales',
        weeklyPeriods: 3,
        type: 'seminar',
        labDuration: 1,
        room: 'Seminar Hall ECE',
        color: '#7c3aed',
      },
      {
        id: 'sub-ec607',
        code: 'EC607',
        name: 'Remedial & GATE Prep',
        facultyName: 'Dr. Kevin Zhao',
        weeklyPeriods: 3,
        type: 'tutorial',
        labDuration: 1,
        room: 'Room ECE-305',
        color: '#64748b',
      },
    ],
  },
];
